name: Packing .NET Assemblies Step
description: Padroniza o pack dos assemblies

runs:
  using: composite
  steps:
  - run: dotnet pack
    shell: bash
  - uses: actions/upload-artifact@v3.1.0
    with:
      name: nuget_assemblies
      path: "**/*.nupkg"
      retention-days: 7
