name: Packing .NET Assemblies Step
description: Padroniza o pack dos assemblies

runs:
  using: composite
  steps:
  - name: Packing Artifacts
    run: dotnet pack
    shell: bash
  - name: Uploading Artifacts
    uses: actions/upload-artifact@v3.1.0
    with:
      name: nuget_assemblies
      path: "**/*.nupkg"
      retention-days: 7
