name: Build .NET Solution Step

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Restore dependencies
      run: dotnet restore    

    - name: Build
      run: dotnet build --no-restore
