name: Check Commit Conventions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-commitlint:

    runs-on: ubuntu-latest

    steps:
    - name: Run commitlint
      run: echo "commitlint run"
