name: Publish Nuget Release

on:
  release:
    types: [released]

jobs:
  build-and-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: ./.github/actions/setup
    - name: Build Solution
      uses: ./.github/actions/build
    - name: Run Tests
      uses: ./.github/actions/tests
    - name: Packing Artifacts
      uses: ./.github/actions/pack

  publish-on-nuget:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: ./.github/actions/setup
    - name: Publish Artifacts
      uses: ./.github/actions/publish